# Generated by Django 4.2.24 on 2025-09-19 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_class_head_teacher'),
        ('students', '0002_rename_student_student_id_idx_students_student_1ff8ed_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_alter_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='考试编码')),
                ('name', models.CharField(max_length=128, verbose_name='考试名称')),
                ('term', models.CharField(max_length=32, verbose_name='学期')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='考试日期')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='schools.grade', verbose_name='年级')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='总分')),
                ('full_score', models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='满分')),
                ('rank_in_class', models.PositiveIntegerField(blank=True, null=True, verbose_name='班内排名')),
                ('rank_in_grade', models.PositiveIntegerField(blank=True, null=True, verbose_name='年级排名')),
                ('passed', models.BooleanField(default=False, verbose_name='是否及格')),
                ('student_name', models.CharField(max_length=64, verbose_name='学生姓名')),
                ('class_name', models.CharField(max_length=64, verbose_name='班级名称')),
                ('course_name', models.CharField(max_length=128, verbose_name='课程名称')),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='schools.class', verbose_name='班级')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='courses.course', verbose_name='课程')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='grades.exam', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.student', verbose_name='学生')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
                'db_table': 'scores',
                'indexes': [models.Index(fields=['exam', 'class_ref'], name='scores_exam_id_ff1ec9_idx'), models.Index(fields=['student'], name='scores_student_8757c6_idx'), models.Index(fields=['course'], name='scores_course__760375_idx')],
                'unique_together': {('exam', 'student', 'course')},
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['term'], name='exams_term_722278_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['name'], name='exams_name_d347f9_idx'),
        ),
    ]
