# Generated by Django 4.2.24 on 2025-09-09 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "teacher_id",
                    models.CharField(max_length=32, unique=True, verbose_name="工号"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("男", "男"), ("女", "女")],
                        default="男",
                        max_length=8,
                        verbose_name="性别",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, unique=True, verbose_name="手机号"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="邮箱"
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="身份证号"
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("在职", "在职"),
                            ("试用", "试用"),
                            ("停职", "停职"),
                            ("离职", "离职"),
                        ],
                        default="在职",
                        max_length=16,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[("全职", "全职"), ("兼职", "兼职"), ("外聘", "外聘")],
                        default="全职",
                        max_length=16,
                    ),
                ),
                ("remark", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "教师",
                "verbose_name_plural": "教师",
                "db_table": "teachers",
                "indexes": [
                    models.Index(
                        fields=["teacher_id"], name="teachers_teacher_456fe5_idx"
                    ),
                    models.Index(fields=["name"], name="teachers_name_13cfbe_idx"),
                    models.Index(fields=["phone"], name="teachers_phone_218f75_idx"),
                ],
            },
        ),
    ]
