# Generated by Django 4.2.24 on 2025-09-09 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0002_class_head_teacher"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("subject", models.CharField(max_length=64, verbose_name="学科")),
                (
                    "duty",
                    models.CharField(
                        choices=[
                            ("任课", "任课"),
                            ("年级主任", "年级主任"),
                            ("教研组长", "教研组长"),
                        ],
                        default="任课",
                        max_length=16,
                        verbose_name="职务",
                    ),
                ),
                (
                    "weekly_hours",
                    models.PositiveIntegerField(default=0, verbose_name="周课时"),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="学年"
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="学期"
                    ),
                ),
                (
                    "class_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_assignments",
                        to="schools.class",
                        verbose_name="班级",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "教师任课",
                "verbose_name_plural": "教师任课",
                "db_table": "teacher_assignments",
                "indexes": [
                    models.Index(
                        fields=["teacher"], name="teacher_ass_teacher_7535f2_idx"
                    ),
                    models.Index(
                        fields=["class_ref"], name="teacher_ass_class_r_5d8573_idx"
                    ),
                    models.Index(
                        fields=["subject"], name="teacher_ass_subject_11f9ed_idx"
                    ),
                ],
            },
        ),
    ]
