# Generated by Django 4.2.24 on 2025-09-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("teachers", "0002_teachingassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachingassignment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_assignments",
                to="courses.course",
            ),
        ),
    ]
