# Generated by Django 4.2.24 on 2025-09-27 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('current_year', models.CharField(max_length=32, verbose_name='学年')),
                ('current_term', models.CharField(max_length=32, verbose_name='学期')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学年学期设置',
                'verbose_name_plural': '学年学期设置',
                'db_table': 'academic_settings',
                'indexes': [models.Index(fields=['current_year'], name='academic_se_current_6a6fbe_idx'), models.Index(fields=['current_term'], name='academic_se_current_36d243_idx')],
            },
        ),
    ]
