# Generated by Django 4.2.24 on 2025-09-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='end_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
