# Generated by Django 4.2.24 on 2025-09-09 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="课程学段"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="课程名称")),
                (
                    "category",
                    models.CharField(
                        choices=[("必修", "必修"), ("选修", "选修")],
                        default="必修",
                        max_length=16,
                    ),
                ),
                (
                    "weekly_hours",
                    models.PositiveIntegerField(default=1, verbose_name="周课时"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="课程简介"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("启用", "启用"), ("停用", "停用")],
                        default="启用",
                        max_length=8,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "db_table": "courses",
                "indexes": [
                    models.Index(fields=["code"], name="courses_code_fa42f1_idx"),
                    models.Index(fields=["name"], name="courses_name_dcd600_idx"),
                ],
            },
        ),
    ]
