# Generated by Django 4.2.24 on 2025-09-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=64, verbose_name='课程学段'),
        ),
    ]
