# Generated by Django 4.2 on 2025-09-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="full_score",
            field=models.PositiveIntegerField(null=True, blank=True, verbose_name="课程分值"),
        ),
    ]


