# Generated by Django 4.2.24 on 2025-09-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_full_score'),
        ('courses', '0002_alter_course_code'),
    ]

    operations = [
    ]
